export const PROCESS_FETCH_MOVIES = 'PROCESS_FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const PROCESS_FETCH_CHARACTERS = 'PROCESS_FETCH_CHARACTERS';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILED = 'FETCH_CHARACTERS_FAILED';
